"use client";

// import type { Metadata } from "next";
import { Montserrat, Montserrat_Alternates } from "next/font/google";
import { ThemeProvider } from "styled-components";

import theme from "@/global/theme";
import Global from "@/global";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const montserrat_alternates = Montserrat_Alternates({
  variable: "--font-montserrat-alternates",
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body className={`${montserrat.variable} ${montserrat_alternates.variable}`}>
          {children}
        </body>
      </html>
      <Global />
    </ThemeProvider>
  );
}
